version: "2.4"
services:
  ingest:
    image: mobile-all:latest
    depends_on:
      - s3
    ports:
      - "9080:9080"
    volumes:
      - ./settings/mobile-ingest.toml:/opt/ingest/etc/settings.toml
    command: /opt/ingest/bin/ingest -c /opt/ingest/etc/settings.toml server
  config:
    image: mobile-all:latest
    depends_on:
      - db-seeder
    ports:
      - "9081:9081"
    volumes:
      - ./settings/mobile-config.toml:/opt/mobile-config/etc/settings.toml
      - ./keypairs/test-config-keypair.bin:/opt/mobile-config/etc/test-config-keypair.bin:ro
    command: /opt/mobile-config/bin/mobile-config -c /opt/mobile-config/etc/settings.toml server
  price:
    image: mobile-all:latest
    depends_on:
      - s3
    volumes:
      - ./settings/mobile-price.toml:/opt/price/etc/settings.toml
    command: /opt/price/bin/price -c /opt/price/etc/settings.toml server
  packet-verifier:
    image: mobile-all:latest
    depends_on:
      - db-seeder
      - s3
    volumes:
      - ./settings/mobile-packet-verifier.toml:/opt/mobile-packet-verifier/etc/settings.toml
      - ./keypairs/test-packet-verifier.bin:/opt/mobile-packet-verifier/etc/test-packet-verifier.bin:ro
    command: /opt/mobile-packet-verifier/bin/mobile-packet-verifier -c /opt/mobile-packet-verifier/etc/settings.toml server
  verifier:
    image: mobile-all:latest
    depends_on:
      - db-seeder
      - s3
    volumes:
      - ./settings/mobile-verifier.toml:/opt/mobile-verifier/etc/settings.toml
      - ./keypairs/test-verifier-keypair.bin:/opt/mobile-verifier/etc/test-verifier-keypair.bin:ro
    command: /opt/mobile-verifier/bin/mobile-verifier -c /opt/mobile-verifier/etc/settings.toml server
  reward-indexer:
    image: mobile-all:latest
    depends_on:
      - db-seeder
      - s3
    volumes:
      - ./settings/mobile-reward-index.toml:/opt/reward-index/etc/settings.toml
    command: /opt/reward-index/bin/reward-index -c /opt/reward-index/etc/settings.toml server
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data
      POSTGRES_DBS: >
        mobile_config_db
        mobile_metadata_db
        mobile_index_db
        mobile_verifier_db
        mobile_packet_verifier_db
    ports:
      - "5432:5432"
    entrypoint:
      - /bin/bash
      - -c
      - |
        for db in $${POSTGRES[@]}
        do
            cat > /docker-entrypoint-initdb.d/$${db}-setup.sql <<EOF
            CREATE DATABASE $$db
                WITH
                OWNER = $$POSTGRES_USER
                ENCODING = 'UTF8'
                LC_COLLATE = 'en_US.utf8'
                LC_CTYPE = 'en_US.utf8'
                TABLESPACE = pg_default
                CONNECTION LIMIT = -1;
        EOF
        done
        docker-entrypoint.sh postgres -c log_statement=all
    volumes:
      - db-data:/data
  db-seeder:
    image: oracle-db-seeder:latest
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432
      STACK: mobile
    depends_on:
      - postgres
  s3:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      EAGER_SERVICE_LOADING: 1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/etc/localstack/init/ready.d

volumes:
  db-data:
