log = "iot_config=debug"
listen = "0.0.0.0:9081"
admin = "141jjqmhrBAE3qtR3ggFwAVcd5StGDRpP6dRRFgsXC7rV32Kngt"
keypair = "/opt/iot-config/etc/test-config-keypair.bin"

[database]
url = "postgres://postgres:postgres@postgres:5432/iot_config_db"
max_connection = 10

[metadata]
url = "postgres://postgres:postgres@postgres:5432/iot_metadata_db"
max_connections = 10

[metrics]
endpoint = "0.0.0.0:19000"