log = "iot_packet_verifier=debug,file_store=info"
org_url = "http://config:9081/"
cache = "/opt/iot-packet-verifier/data"
burn_period = 1
config_keypair = "/opt/iot-packet-verifier/etc/test-packet-verifier-keypair.bin"
enable_solana_integration = false
minimum_allowed_balance = 3_500_000
monitor_funds_period = 30
start_after = 0

[iot_config_client]
url = "http://config:9081/"
signing_keypair = "/opt/iot-packet-verifier/etc/test-packet-verifier-keypair.bin"
config_pubkey = "13HzR2frS8r5b5j3JyTMjoaRVbiUn5m9Vu181C5JuodioVJNLk2"

[database]
url = "postgres://postgres:postgres@postgres:5432/packet_verifier_db"
max_connections = 10

[ingest]
bucket = "iot-packet-ingest"
region = "us-east-1"
endpoint = "http://s3:4566"

[output]
bucket = "iot-packet-verifier"
region = "us-east-1"
endpoint = "http://s3:4566"

[metrics]
endpoint = "0.0.0.0:19000"
