log = "reward_index=debug,file_store=info"
interval = 900
mode = "iot"
operation_fund_key = "iot_operations_fund"
start_after = 0

[database]
url = "postgres://postgres:postgres@postgres:5432/iot_index_db"
max_connections = 10

[verifier]
bucket = "iot-verifier"
region = "us-east-1"
endpoint = "http://s3:4566"

[metrics]
endpoint = "0.0.0.0:19000"
