log = "price=debug,file_store=info"
cache = "/opt/price/data"
source = "quicknode.url.com"
interval = 60

[cluster]
name = "devnet"
hnt_price_key = "ECtrQnxTXy6E22JG9WZtbvo6etdRnMfmUps4ueLwimHv"
mobile_price_key = "CkCLWNUhhtWPKid69qJaw3MY9Tr2XD9vAUiqUroQHkZJ"

[output]
bucket = "mobile-price"
region = "us-east-1"
endpoint = "http://s3:4566"

[metrics]
endpoint = "0.0.0.0:19000"